const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),C={blue:'#173e83',red:'#db392d',cream:'#f8edcf',water:'#53c4dd',dark:'#102952'};
let state='ready',score=0,misses=0,clog=0,combo=0,roundStart=0,lastSpawn=0,lastFrame=0,stageStart=0,sound=false,audio,bossHits=0;
const slots=[{x:60,y:125},{x:160,y:125},{x:260,y:125},{x:60,y:205},{x:160,y:205},{x:260,y:205}],enemies=[],fx=[];
let enemyId=0,lastType=-1,bossShake=0;
const names=['물티슈','머리카락','기름때','음식물','치실','면봉'];
canvas.height=280;canvas.style.aspectRatio='320 / 280';$('tap').remove();
document.querySelector('.intro').textContent='배관 안에 나타나는 이물질을 터치로 제거하세요!';
document.querySelector('.dots').outerHTML='<span id="score">제거 0 · 콤보 0</span>';
const controls=document.createElement('div');controls.innerHTML='<div class="clog-track" aria-label="막힘 게이지"><div id="clog-bar"></div></div><p id="clog-label">막힘 0%</p><div id="targets"></div><button class="action primary" id="start-game">배관 지키기 시작!</button><button class="action dispatch" id="dispatch" hidden>내집배관솔루션 출동!</button>';
document.querySelector('.hud').after(controls);
const style=document.createElement('style');style.textContent='.screen{touch-action:manipulation}#targets{position:absolute;inset:0;pointer-events:none}.target{position:absolute;width:21%;height:23%;pointer-events:auto;background:transparent;border:0;color:transparent;touch-action:manipulation}.target:focus-visible{outline:3px solid #db392d}.clog-track{height:14px;border:3px solid #173e83;background:#f8edcf}#clog-bar{height:100%;width:0;background:#db392d;transition:width .15s}#clog-label{font-size:13px;font-weight:bold;margin:6px 0 12px}.dispatch{width:100%;background:#db392d;color:#f8edcf;border-color:#173e83;box-shadow:4px 4px 0 #173e83;font-size:18px}.dispatch[hidden],#start-game[hidden]{display:none}h1{font-size:clamp(28px,7vw,38px);margin-top:16px}.intro{font-size:14px}main{padding-top:18px}.hud{margin:12px 0}#message{font-size:16px;min-height:48px}';document.head.append(style);
document.querySelector('.screen').append($('targets'));
document.querySelector('.screen').append($('dispatch'));
$('dispatch').textContent='비상! 내집배관솔루션 출동';
const bossTarget=document.createElement('button');bossTarget.className='target';bossTarget.style.cssText='left:15%;top:36%;width:72%;height:40%;display:none';bossTarget.setAttribute('aria-label','슬러지 보스 타격');bossTarget.onclick=()=>hit(-1);$('targets').append(bossTarget);
const overlayStyle=document.createElement('style');overlayStyle.textContent='.dispatch{position:absolute;z-index:5;left:8%;top:43%;width:84%;font-size:clamp(14px,4vw,18px);padding:16px 8px;animation:alarm .7s steps(2,end) infinite}.target{z-index:2}@keyframes alarm{50%{box-shadow:0 0 0 5px #f8edcf}}@media(prefers-reduced-motion:reduce){.dispatch{animation:none}}';document.head.append(overlayStyle);
function removeEnemy(i){enemies[i].button.remove();enemies.splice(i,1)}
function clearEnemies(){while(enemies.length)removeEnemy(0)}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function text(s,x,y,size=12,c=C.blue){ctx.fillStyle=c;ctx.font='bold '+size+'px sans-serif';ctx.textAlign='center';ctx.fillText(s,x,y)}
function tone(f,d=.07){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function update(){ $('score').textContent='제거 '+score+' · 콤보 '+combo;$('clog-bar').style.width=clog+'%';$('clog-label').textContent='막힘 '+Math.round(clog)+'%'; }
function begin(t=performance.now()){state='playing';score=0;misses=0;clog=0;combo=0;bossHits=0;lastType=-1;clearEnemies();bossTarget.style.display='none';fx.length=0;roundStart=t;lastSpawn=t-650;stageStart=t;$('result').classList.remove('show');$('start-game').hidden=true;$('dispatch').hidden=true;$('message').textContent='배관 안을 살펴보세요! 사라지기 전에 톡!';update()}
function spawn(t){if(enemies.length>=5)return;let p;for(let tries=0;tries<40;tries++){const candidate={x:40+Math.random()*240,y:(Math.random()<.5?119:200)+(Math.random()-.5)*10};if(enemies.every(e=>Math.abs(e.x-candidate.x)>55||Math.abs(e.y-candidate.y)>55)){p=candidate;break}}if(!p)return;const types=names.map((_,i)=>i).filter(i=>i!==lastType&&!enemies.some(e=>e.type===i));if(!types.length)return;const type=types[Math.floor(Math.random()*types.length)];lastType=type;const e={id:++enemyId,...p,type,expires:t+Math.max(850,1600-(t-roundStart)*.029),born:t};const b=document.createElement('button');b.className='target';b.style.cssText='left:'+((e.x-27)/320*100)+'%;top:'+((e.y-30)/280*100)+'%;width:16.875%;height:21.43%';b.setAttribute('aria-label',names[type]+' 제거');b.onclick=()=>hit(e.id);e.button=b;enemies.push(e);$('targets').append(b)}
function boss(t){state='boss';stageStart=t;bossHits=0;clearEnemies();clog=100;update();bossTarget.style.display='block';$('phase').textContent='FINAL BOSS · 꽉 막힌 슬러지';$('message').textContent='슬러지를 직접 두드려보세요! 타격 0 / 9';$('dispatch').hidden=true;tone(100,.25)}
function hit(id,t=performance.now()){if(state==='boss'){if(id!==-1||bossHits>=9)return false;bossHits++;bossShake=t;fx.push({x:110+Math.random()*100,y:145,t,label:bossHits<9?'단단하다!':'비상 출동 해제!',c:C.red});$('message').textContent=bossHits<9?'꿈쩍도 안 해요! 타격 '+bossHits+' / 9':'혼자서는 안 돼요! 비상 버튼으로 내집을 불러주세요.';if(bossHits===9){$('dispatch').hidden=false;bossTarget.style.display='none'}tone(100+bossHits*12);return true}if(state!=='playing')return false;const i=enemies.findIndex(e=>e.id===id);if(i<0)return false;const e=enemies[i];if(t>=e.expires)return false;removeEnemy(i);score++;combo++;clog=Math.max(0,clog-3);fx.push({x:e.x,y:e.y-20,t,label:combo>=3?combo+' COMBO!':'+1',c:C.red});tone(400+Math.min(combo,8)*55);update();return true}
function dispatch(t=performance.now()){if(state!=='boss'||bossHits<9)return false;state='arriving';stageStart=t;$('dispatch').hidden=true;bossTarget.style.display='none';$('phase').textContent='내집배관솔루션 · 출동 중';$('message').textContent='파란 내집 트럭이 도착합니다!';tone(440,.12);return true}
function tick(t){if(state==='playing'){let e=t-roundStart;$('phase').textContent='남은 시간 '+Math.max(0,Math.ceil((18000-e)/1000))+'초';for(let i=enemies.length-1;i>=0;i--)if(t>=enemies[i].expires){removeEnemy(i);misses++;combo=0;clog=Math.min(100,clog+9);update()}if(t-lastSpawn>Math.max(360,820-e*.024)){spawn(t);lastSpawn=t}if(e>=18000||clog>=100)boss(t)}else if(state==='arriving'&&t-stageStart>1400){state='jet';stageStart=t;$('message').textContent='고압세척! 슬러지를 시원하게 밀어냅니다.';tone(180,.3)}else if(state==='jet'){clog=Math.max(0,100-(t-stageStart)/20);update();if(t-stageStart>2200){state='done';clog=0;update();$('result').classList.add('show');$('phase').textContent='MISSION CLEAR · 배관 흐름 회복';$('message').textContent=score+'개 제거! 마지막 슬러지는 내집이 해결했습니다.';tone(880,.2)}}}
function truck(x,y,t){rect(x,y+12,28,24,C.blue);rect(x+8,y+4,20,22,C.blue);rect(x+12,y+8,13,12,C.cream);rect(x+28,y+10,62,26,C.blue);rect(x+32,y+14,54,17,C.cream);text('내집배관',x+59,y+26,9);[17,74].forEach(w=>{rect(x+w-6,y+32,12,12,C.dark);rect(x+w-3,y+35,6,6,C.cream)});rect(x+44,y,6,10,C.blue);rect(x+43,y-3,26,6,C.blue)}
function enemy(e,t){const x=e.x,y=e.y-20+Math.max(0,1-(t-e.born)/130)*12;
if(e.type===0){rect(x-19,y,34,24,'#b0b9c0');rect(x-16,y-3,31,24,'#f7f5e7');rect(x-11,y+2,20,3,'#cdd0c8');rect(x-11,y+9,15,3,'#cdd0c8');rect(x+11,y+15,11,7,'#f7f5e7')}
if(e.type===1){for(let k=0;k<6;k++){rect(x-20+k*6,y+(k%3)*4,4,23,'#403247');rect(x-17+k*6,y+18,9,4,'#403247')}rect(x-13,y+6,23,4,'#6d4c56')}
if(e.type===2){rect(x-19,y+8,38,18,'#ae751d');rect(x-14,y+2,29,23,'#e5ad37');rect(x-6,y-4,12,14,'#f7c952');rect(x-11,y+8,8,4,'#ffe499');rect(x+9,y+12,8,6,'#cb8b22')}
if(e.type===3){rect(x-17,y+3,17,15,'#db7044');rect(x+2,y+10,17,13,'#b34630');rect(x-10,y+19,12,7,'#e7b568');rect(x+3,y-3,12,9,'#78a957');rect(x+8,y-7,4,8,'#527740')}
if(e.type===4){rect(x-18,y+1,22,4,'#eddce8');rect(x-18,y+1,4,18,'#eddce8');rect(x-18,y+16,31,4,'#eddce8');rect(x+9,y+16,4,11,'#eddce8');rect(x+9,y+24,13,4,'#eddce8');rect(x-13,y+5,12,3,'#a178ad')}
if(e.type===5){rect(x-16,y+21,32,5,'#57a6c6');rect(x-21,y+18,10,11,'#f8f6e9');rect(x+12,y+18,10,11,'#f8f6e9');rect(x-15,y-1,5,23,'#c6dee1');rect(x-18,y-5,11,10,'#f8f6e9')}
text(names[e.type],x,e.y+19,10,C.cream);rect(x-19,e.y+24,38,3,'#718999');rect(x-19,e.y+24,Math.round(38*Math.max(0,(e.expires-t)/(e.expires-e.born))),3,C.red)}
function render(t){requestAnimationFrame(render);const dt=Math.min(50,t-lastFrame);lastFrame=t;tick(t);rect(0,0,320,280,'#e2eddf');rect(0,0,320,58,'#d2e5e7');for(let x=0;x<320;x+=42)rect(x,63,20,3,C.cream);rect(0,58,320,4,C.blue);rect(0,69,320,5,'#a7b5a4');text('NAEJIP PIPE RESCUE',160,267,11);
[119,200].forEach(y=>{rect(8,y-35,304,72,C.blue);rect(14,y-29,292,60,C.dark);rect(14,y-28,292,4,'#628199');rect(14,y+25,292,4,'#628199');[19,289].forEach(x=>{rect(x,y-37,8,76,'#7493aa');rect(x+2,y-36,2,74,C.cream)})});rect(276,138,30,44,C.blue);rect(282,138,18,44,C.dark);
if(['ready','playing'].includes(state)){truck(10,7,t);enemies.forEach(e=>enemy(e,t));if(state==='ready'){text('랜덤 이물질을 잡아라!',160,153,14);text('18초 동안 배관을 지켜주세요',160,175,12)}}
if(['boss','arriving','jet'].includes(state)){const sh=state==='jet'||t-bossShake<150?Math.sin(t/24)*3:Math.sin(t/160)*2;rect(29,105,262,99,C.dark);rect(34,110,252,89,C.cream);rect(44,142,231,25,'#776849');const amount=state==='jet'?clog/100:1,w=Math.round(183*amount);rect(83+sh,113,w,80,'#69533f');for(let k=0;k<Math.ceil(w/17);k++)rect(83+k*17+sh,106+(k%3)*9,Math.min(15,w-k*17),87,'#806940');if(amount>.45){rect(107+sh,132,21,14,C.cream);rect(190+sh,132,21,14,C.cream);rect(120+sh,135,7,11,C.red);rect(190+sh,135,7,11,C.red);rect(140+sh,162,37,9,C.dark);}text('슬러지 BOSS',160,232,15,C.red);if(state==='boss'){text('타격 '+bossHits+' / 9 · 단단함 MAX',160,92,12,C.red)}if(state==='arriving')truck(-95+Math.min(1,(t-stageStart)/1100)*204,7,t);if(state==='jet'){truck(109,7,t);rect(146,48,6,57,C.water);rect(39,152,Math.round(238*(1-amount)),13,C.water);for(let k=0;k<10;k++)rect(39+(t/5+k*23)%239,155,9,4,C.cream)}}
if(state==='done'){truck(109,7,t);slots.forEach(p=>{rect(p.x-20,p.y-13,40,10,C.water);rect(p.x-10,p.y-10,12,3,C.cream)});text('뻥! 흐름 회복!',160,152,23,C.blue);text('막혔어? 내집 간다!',160,180,15,C.red)}
for(let i=fx.length-1;i>=0;i--){let f=fx[i];if(t-f.t>700){fx.splice(i,1);continue}text(f.label,f.x,f.y-(t-f.t)/30,12,f.c)} }
$('start-game').onclick=()=>begin();$('dispatch').onclick=()=>dispatch();$('replay').onclick=()=>begin();$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'소리 ON':'소리 OFF';$('sound').setAttribute('aria-pressed',String(sound));tone(440)};
$('save').onclick=()=>{const u=URL.createObjectURL(new Blob(['BEGIN:VCARD\r\nVERSION:3.0\r\nFN:내집배관솔루션\r\nTEL;TYPE=WORK,VOICE:010-6858-3993\r\nEND:VCARD\r\n'],{type:'text/vcard;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='내집배관솔루션.vcf';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'){state='paused';stageStart=performance.now();$('start-game').hidden=false;$('start-game').textContent='이어서 플레이';$('message').textContent='잠깐 멈췄어요.'}else if(!document.hidden&&state==='paused'){$('start-game').onclick=()=>{let delta=performance.now()-stageStart;roundStart+=delta;lastSpawn+=delta;enemies.forEach(e=>{e.expires+=delta;e.born+=delta});state='playing';$('start-game').hidden=true;$('start-game').textContent='배관 지키기 시작!';$('start-game').onclick=()=>begin()}}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_game_state',description:'Read the current game round.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,score,clog,bossHits,enemies:enemies.map(e=>({id:e.id,type:names[e.type],x:e.x,y:e.y}))})})}catch{}}
$('message').textContent='사라지기 전에 잡으세요! 마지막엔 슬러지 보스가 기다립니다.';update();requestAnimationFrame(render);