const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),C={blue:'#173e83',red:'#db392d',cream:'#f8edcf',water:'#53c4dd',dark:'#102952'};
let state='ready',score=0,misses=0,clog=0,combo=0,roundStart=0,lastSpawn=0,lastFrame=0,stageStart=0,sound=false,audio,bossHits=0;
const slots=[{x:60,y:125},{x:160,y:125},{x:260,y:125},{x:60,y:205},{x:160,y:205},{x:260,y:205}],enemies=[],fx=[];
let enemyId=0,lastType=-1,bossShake=0;
const GOAL=20,ALARM_DELAY=2000;
const names=['물티슈','머리카락','기름때','음식물','휴지','면봉','오리 장난감'];
const spriteKeys=['wipe','hair','grease','food','tissue','swab','duck'],sprites={};
const reducedMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function sprite(key,frame,x,y,w,h){const im=sprites[key];if(!im?.complete||!im.naturalWidth)return;const fw=im.naturalWidth/4;ctx.imageSmoothingEnabled=false;ctx.drawImage(im,frame*fw,0,fw,im.naturalHeight,Math.round(x),Math.round(y),w,h)}
for(const key of [...spriteKeys,'boss','truck-right','truck-spray','water-jet','emergency']){const im=new Image();im.src='assets/sprites/'+key+'.png';sprites[key]=im}
canvas.height=280;canvas.style.aspectRatio='320 / 280';$('tap').remove();
const coupon=document.createElement('div');coupon.id='coupon';coupon.innerHTML='<p class="result-copy">미션 완료! 내시경 점검 0원 쿠폰 획득</p><img src="assets/coupon.png" alt="내집배관솔루션 배관 내시경 0원 쿠폰. 010-6858-3993. 배관 문제로 출동 후 현장 진단에 내시경이 필요할 때 무료 제공, 내시경 점검 비용에만 적용." style="display:block;width:100%;height:auto">';
coupon.hidden=true;document.querySelector('.screen').append(coupon);const saveHint=document.createElement('p');saveHint.id='save-hint';saveHint.textContent='쿠폰 이미지 저장 버튼으로 내려받으세요.';$('result').prepend(saveHint);document.querySelector('.result-copy').textContent='미션 완료! 내시경 점검 0원 쿠폰 획득';$('save').textContent='쿠폰 이미지 저장';
const couponStyle=document.createElement('style');couponStyle.textContent='#coupon{position:absolute;inset:0;z-index:6;background:#082f50;display:flex;flex-direction:column;justify-content:center;padding:7px;animation:coupon-reveal .65s ease-out}#coupon[hidden]{display:none}#coupon .result-copy{color:#fff;text-align:center;font-size:clamp(12px,3.6vw,17px);margin:0 0 7px}#coupon img{max-height:85%;object-fit:contain}#alarm-screen{position:fixed;inset:0;z-index:100;background:rgba(219,57,45,.32);pointer-events:none;animation:danger-flash 1s ease-in-out infinite}#alarm-screen[hidden]{display:none}@keyframes danger-flash{0%,100%{opacity:.1}50%{opacity:1}}@media(prefers-reduced-motion:reduce){#alarm-screen{animation:none;opacity:.5}}#save-hint{font-size:12px;line-height:1.6}#dispatch img{width:48px;height:48px;object-fit:none;object-position:left;image-rendering:pixelated}@keyframes coupon-reveal{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){#coupon{animation:none}}';document.head.append(couponStyle);
const alarmScreen=document.createElement('div');alarmScreen.id='alarm-screen';alarmScreen.hidden=true;alarmScreen.setAttribute('aria-hidden','true');document.body.append(alarmScreen);
document.querySelector('.intro').textContent='배관 안 이물질 20개를 제거하고 보스에 도전하세요!';
document.querySelector('.dots').outerHTML='<span id="score">제거 0 · 콤보 0</span>';
const controls=document.createElement('div');controls.innerHTML='<div class="clog-track" aria-label="막힘 게이지"><div id="clog-bar"></div></div><p id="clog-label">막힘 0%</p><div id="targets"></div><button class="action primary" id="start-game">배관 지키기 시작!</button><button class="action dispatch" id="dispatch" hidden>내집배관솔루션 출동!</button>';
document.querySelector('.hud').after(controls);
const hudStyle=document.createElement('style');hudStyle.textContent='main:has(#result.show) .hud{display:flex;flex-direction:column;align-items:center;gap:5px;text-align:center;line-height:1.5}main:has(#result.show) .hud #phase,main:has(#result.show) .hud #score{white-space:nowrap;font-size:clamp(11px,3.2vw,14px)}';document.head.append(hudStyle);
const style=document.createElement('style');style.textContent='.screen{touch-action:manipulation}#targets{position:absolute;inset:0;pointer-events:none}.target{position:absolute;width:21%;height:23%;pointer-events:auto;background:transparent;border:0;color:transparent;touch-action:manipulation}.target:focus-visible{outline:3px solid #db392d}.clog-track{height:14px;border:3px solid #173e83;background:#f8edcf}#clog-bar{height:100%;width:0;background:#db392d;transition:width .15s}#clog-label{font-size:13px;font-weight:bold;margin:6px 0 12px}.dispatch{width:100%;background:#db392d;color:#f8edcf;border-color:#173e83;box-shadow:4px 4px 0 #173e83;font-size:18px}.dispatch[hidden],#start-game[hidden]{display:none}h1{font-size:clamp(28px,7vw,38px);margin-top:16px}.intro{font-size:14px}main{padding-top:18px}.hud{margin:12px 0}#message{font-size:16px;min-height:48px}.clear-line{white-space:nowrap;font-size:clamp(11px,3.5vw,16px)}';document.head.append(style);
document.querySelector('.screen').append($('targets'));
document.querySelector('.screen').append($('dispatch'));
$('dispatch').innerHTML='<span class="emergency-icon" aria-hidden="true"></span>비상! 내집배관솔루션 출동';
const bossTarget=document.createElement('button');bossTarget.className='target';bossTarget.style.cssText='left:5%;top:20%;width:90%;height:70%;display:none';bossTarget.setAttribute('aria-label','슬러지 보스 타격');bossTarget.onclick=()=>hit(-1);$('targets').append(bossTarget);
const overlayStyle=document.createElement('style');overlayStyle.textContent='.emergency-icon{display:block;width:64px;height:64px;margin:0 auto 4px;background:url(assets/sprites/emergency.png) 0 0/256px 64px;image-rendering:pixelated}.dispatch{position:absolute;z-index:5;left:8%;top:43%;width:84%;font-size:clamp(14px,4vw,18px);padding:16px 8px;animation:alarm .7s steps(2,end) infinite}.target{z-index:2}@keyframes alarm{50%{box-shadow:0 0 0 5px #f8edcf}}@media(prefers-reduced-motion:reduce){.dispatch{animation:none}}';document.head.append(overlayStyle);
function sheetFrame(key,frame,x,y,w,h){const im=sprites[key];if(!im?.complete||!im.naturalWidth)return;const fw=im.naturalWidth/2,fh=im.naturalHeight/2;ctx.imageSmoothingEnabled=false;ctx.drawImage(im,(frame%2)*fw,Math.floor(frame/2)*fh,fw,fh,Math.round(x),Math.round(y),w,h)}
function waterJet(t,x,y,width,height){const im=sprites['water-jet'];if(!im?.complete||!im.naturalWidth)return;const frame=reducedMotion?1:1+Math.floor(t/110)%3;ctx.imageSmoothingEnabled=false;ctx.drawImage(im,0,im.naturalHeight*frame/4,im.naturalWidth,im.naturalHeight/4,x,y,width,height)}
let audioGain,soundRequest=0;
function soundLabel(){const button=$('sound');button.textContent=sound?'소리 켜짐':'소리 꺼짐';button.setAttribute('aria-pressed',String(sound));button.setAttribute('aria-label',sound?'소리 켜짐 · 눌러 끄기':'소리 꺼짐 · 눌러 켜기')}
async function toggleSound(){const request=++soundRequest;if(sound){sound=false;if(audioGain)audioGain.gain.setValueAtTime(0,audio.currentTime);soundLabel();return}try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(!audioGain){audioGain=audio.createGain();audioGain.connect(audio.destination)}await audio.resume();if(request!==soundRequest)return;sound=audio.state==='running';audioGain.gain.setValueAtTime(sound?1:0,audio.currentTime);soundLabel();if(sound)tone(440)}catch{sound=false;soundLabel();$('message').textContent='소리를 켤 수 없어요. 브라우저 소리 설정을 확인해주세요.'}}
function removeEnemy(i){enemies[i].button.remove();enemies.splice(i,1)}
function clearEnemies(){while(enemies.length)removeEnemy(0)}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function text(s,x,y,size=12,c=C.blue){ctx.fillStyle=c;ctx.font='bold '+size+'px sans-serif';ctx.textAlign='center';ctx.fillText(s,x,y)}
function tone(f,d=.07){if(!sound||!audioGain||audio.state!=='running')return;try{const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audioGain);o.start();o.stop(audio.currentTime+d);o.onended=()=>{o.disconnect();g.disconnect()}}catch{}}
function update(){ $('score').textContent='제거 '+score+' / '+GOAL+' · 콤보 '+combo;$('clog-bar').style.width=clog+'%';$('clog-label').textContent='막힘 '+Math.round(clog)+'%'; }
function begin(t=performance.now()){state='playing';coupon.hidden=true;alarmScreen.hidden=true;score=0;misses=0;clog=0;combo=0;bossHits=0;lastType=-1;clearEnemies();bossTarget.style.display='none';fx.length=0;roundStart=t;lastSpawn=t-650;stageStart=t;$('result').classList.remove('show');$('start-game').hidden=true;$('dispatch').hidden=true;$('message').textContent='배관 안을 살펴보세요! 사라지기 전에 톡!';update()}
function spawn(t){if(enemies.length>=5)return;let p;for(let tries=0;tries<40;tries++){const candidate={x:40+Math.random()*240,y:(Math.random()<.5?119:200)+(Math.random()-.5)*10};if(enemies.every(e=>Math.abs(e.x-candidate.x)>80||Math.abs(e.y-candidate.y)>70)){p=candidate;break}}if(!p)return;const types=names.map((_,i)=>i).filter(i=>i!==lastType&&!enemies.some(e=>e.type===i));if(!types.length)return;const type=types[Math.floor(Math.random()*types.length)];lastType=type;const e={id:++enemyId,...p,type,expires:t+Math.max(850,1600-(t-roundStart)*.029),born:t};const b=document.createElement('button');b.className='target';b.style.cssText='left:'+((e.x-40)/320*100)+'%;top:'+((e.y-40)/280*100)+'%;width:25%;height:28.57%';b.setAttribute('aria-label',names[type]+' 제거');b.onclick=()=>hit(e.id);e.button=b;enemies.push(e);$('targets').append(b)}
function boss(t){fx.length=0;state='boss';stageStart=t;bossHits=0;clearEnemies();clog=100;update();bossTarget.style.display='block';$('phase').textContent='FINAL BOSS · 꽉 막힌 슬러지';$('message').textContent='슬러지를 직접 두드려보세요! 타격 0 / 9';$('dispatch').hidden=true;tone(100,.25)}
function hit(id,t=performance.now()){if(state==='boss'){if(id!==-1||bossHits>=9)return false;bossHits++;bossShake=t;fx.push({x:110+Math.random()*100,y:145,t,label:bossHits<9?'단단하다!':'비상 상황!',c:C.red});$('message').textContent=bossHits<9?'꿈쩍도 안 해요! 타격 '+bossHits+' / 9':'혼자서는 안 돼요! 비상 버튼으로 내집을 불러주세요.';if(bossHits===9){state='alarm';stageStart=t;alarmScreen.hidden=false;$('dispatch').hidden=true;bossTarget.style.display='none';$('message').textContent='비상! 슬러지가 너무 단단합니다. 출동 요청 준비 중…';$('phase').textContent='비상 경보 · 잠시 기다려주세요'}tone(100+bossHits*12);return true}if(state!=='playing')return false;const i=enemies.findIndex(e=>e.id===id);if(i<0)return false;const e=enemies[i];if(t>=e.expires)return false;removeEnemy(i);score++;combo++;clog=Math.max(0,clog-3);fx.push({sprite:spriteKeys[e.type],x:e.x,y:e.y-20,t,label:combo>=3?combo+' COMBO!':'+1',c:C.red});tone(400+Math.min(combo,8)*55);update();if(score>=GOAL)boss(t);return true}
function dispatch(t=performance.now()){if(state!=='boss'||bossHits<9)return false;state='arriving';stageStart=t;$('dispatch').hidden=true;bossTarget.style.display='none';$('phase').textContent='내집배관솔루션 · 출동 중';$('message').textContent='파란 내집 트럭이 도착합니다!';tone(440,.12);return true}
function tick(t){if(state==='playing'){let e=t-roundStart;$('phase').textContent='목표 '+GOAL+'개 · 남은 '+Math.max(0,GOAL-score)+'개';for(let i=enemies.length-1;i>=0;i--)if(t>=enemies[i].expires){removeEnemy(i);misses++;combo=0;clog=Math.min(100,clog+9);update()}if(t-lastSpawn>Math.max(360,820-e*.024)){spawn(t);lastSpawn=t}}else if(state==='alarm'&&t-stageStart>=ALARM_DELAY){state='boss';alarmScreen.hidden=true;$('dispatch').hidden=false;$('phase').textContent='비상 출동 요청 가능';$('message').textContent='이제 비상 버튼을 눌러 내집배관솔루션을 불러주세요.'}else if(state==='arriving'&&t-stageStart>1400){state='jet';stageStart=t;$('message').textContent='고압세척! 슬러지를 시원하게 밀어냅니다.';tone(180,.3)}else if(state==='jet'){clog=Math.max(0,100-(t-stageStart)/20);update();if(t-stageStart>2200){state='sweep';stageStart=t;$('message').textContent='큰 물줄기로 마무리! 쿠폰이 곧 나타납니다.'}}else if(state==='sweep'&&t-stageStart>1250){state='done';coupon.hidden=false;clog=0;update();$('result').classList.add('show');$('phase').textContent='MISSION CLEAR · 배관 흐름 회복';$('message').innerHTML='<span class="clear-line">모든 이물질 제거! 마지막 슬러지는</span><br><span class="clear-line">내집배관솔루션이 해결했습니다.</span>';tone(880,.2)}}
function truck(x,y,t){const spraying=state==='jet';const frame=reducedMotion?0:spraying?1+Math.floor(t/130)%3:state==='arriving'?Math.floor(t/140)%4:0;sheetFrame(spraying?'truck-spray':'truck-right',frame,x,y,128,64)}
function enemy(e,t){const frame=reducedMotion?0:Math.floor((t-e.born)/240)%2;sprite(spriteKeys[e.type],frame,e.x-32,e.y-27,64,64);const labelWidth=names[e.type].length*10+12;rect(e.x-labelWidth/2,e.y-43,labelWidth,16,C.cream);text(names[e.type],e.x,e.y-31,10,C.dark);rect(e.x-20,e.y+38,40,3,'#718999');rect(e.x-20,e.y+38,40*Math.max(0,(e.expires-t)/(e.expires-e.born)),3,C.red)}
function render(t){requestAnimationFrame(render);const dt=Math.min(50,t-lastFrame);lastFrame=t;tick(t);rect(0,0,320,280,C.cream);text('NAEJIP PIPE RESCUE',160,267,11);
[119,200].forEach(y=>{rect(8,y-35,304,72,C.blue);rect(14,y-29,292,60,C.dark);rect(14,y-28,292,4,'#628199');rect(14,y+25,292,4,'#628199');[19,289].forEach(x=>{rect(x,y-37,8,76,'#7493aa');rect(x+2,y-36,2,74,C.cream)})});rect(276,138,30,44,C.blue);rect(282,138,18,44,C.dark);
if(['ready','playing'].includes(state)){truck(7,0,t);enemies.forEach(e=>enemy(e,t));if(state==='ready'){text('랜덤 이물질을 잡아라!',160,153,14);text('이물질 20개를 제거하세요',160,175,12)}}
if(['boss','alarm','arriving','jet'].includes(state)){const sh=!reducedMotion&&t-bossShake<150?Math.sin(t/24)*3:0;const amount=state==='jet'?clog/100:1;const frame=state==='jet'?3:t-bossShake<150?2:Math.floor(t/1800)%2;sprite('boss',frame,10+sh,-20,300,300);rect(76,243,168,23,C.dark);text('슬러지 BOSS',160,260,15,C.cream);if(state==='boss')rect(62,76,196,22,C.dark);if(state==='boss')text('타격 '+bossHits+' / 9 · 단단함 MAX',160,92,12,C.cream);if(state==='arriving')truck(-128+Math.min(1,(t-stageStart)/1100)*135,0,t);if(state==='jet'){truck(7,0,t);const reach=Math.min(1,(t-stageStart)/500);waterJet(t,122,17,198*reach,30);ctx.save();ctx.globalAlpha=.9;waterJet(t,0,107,320*reach,58);waterJet(t+110,0,185,320*reach,58);ctx.restore()}}
if(state==='sweep'){const p=Math.min(1,(t-stageStart)/1100),front=p*430;rect(0,0,Math.min(front,320),280,C.water);for(let k=0;k<24;k++){const yy=k*13;rect(front-35-Math.sin(k+t/90)*18,yy,36,12,'#b7f4fa');rect(front-130-(k%4)*24,yy+3,45,4,C.cream)}text('시원하게 뻥!',160,142,24,C.dark)}
if(state==='done'){truck(109,7,t);slots.forEach(p=>{rect(p.x-20,p.y-13,40,10,C.water);rect(p.x-10,p.y-10,12,3,C.cream)});text('뻥! 흐름 회복!',160,152,23,C.cream);text('막혔어? 내집 간다!',160,180,15,C.red)}
for(let i=fx.length-1;i>=0;i--){let f=fx[i];if(t-f.t>700){fx.splice(i,1);continue}if(f.sprite&&t-f.t<360)sprite(f.sprite,t-f.t<140?2:3,f.x-40,f.y-20,80,80);text(f.label,f.x,f.y-(t-f.t)/30,12,f.c)} }
$('start-game').onclick=()=>begin();$('dispatch').onclick=()=>dispatch();$('replay').onclick=()=>begin();$('sound').onclick=toggleSound;soundLabel();
$('save').onclick=()=>{const a=document.createElement('a');a.href='assets/coupon.png';a.download='내집배관솔루션_내시경점검_0원쿠폰.png';document.body.append(a);a.click();a.remove();$('save-hint').textContent='쿠폰 이미지 다운로드를 요청했어요. 모바일에서 이미지가 열리면 길게 눌러 사진에 저장하세요.'};

document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'){state='paused';stageStart=performance.now();$('start-game').hidden=false;$('start-game').textContent='이어서 플레이';$('message').textContent='잠깐 멈췄어요.'}else if(!document.hidden&&state==='paused'){$('start-game').onclick=()=>{let delta=performance.now()-stageStart;roundStart+=delta;lastSpawn+=delta;enemies.forEach(e=>{e.expires+=delta;e.born+=delta});state='playing';$('start-game').hidden=true;$('start-game').textContent='배관 지키기 시작!';$('start-game').onclick=()=>begin()}}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_game_state',description:'Read the current game round.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,score,clog,bossHits,enemies:enemies.map(e=>({id:e.id,type:names[e.type],x:e.x,y:e.y}))})})}catch{}}
$('message').textContent='이물질 20개를 제거하면 슬러지 보스가 나타납니다.';update();requestAnimationFrame(render);
